### ISSUE TITLE
Decrypt Chrome Cookies

### ISSUE THREAD

**Issue by anonymouz4** [AlessandroZ/LaZagneForensic#10]
In the same directory as the "Login Data" File, there is also the Cookies File.

As far as I know, it uses the same Encryption Method (`Win CryptUnprotectData()`).

Would it be possible to just also decrypt this file, since I would assume that it's not a huge effort but would really help out?

**Update:**
Since it doesn't seem to be much activity on this project any more, I've tried to write my own module.
Decrypting works fine, problem is how they can be imported again.
Does anybody know if I can encrypt them again with a dpapi blob from a different user, or does anyone have a better idea on how to import them to a different machine?

**Comment by AlessandroZ** [comment]
Hi, at first I wanted to create another project dedicated to retrieve cookies from all browsers. But then, I have changed my mind. So your PR is a good start, so thanks for it. 

I should rework a little bit some functions, because Lazagne implements lots more of application (and lots of bugs fix) than LazagneForensic. 
For example, the chrome module has been rebuild to manage [all web browsers](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/chromium_based.py#L135) that use the same way to store creds (not only chrome browser). Same thing for [firefox](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/mozilla.py#L475). 

I don't have time to take a look on it, but if you are interested to add it, feel free. Anyway, thanks for your work. :+1:
